export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="arrow"
plugins=(z extract git zsh-autosuggestions zsh-syntax-highlighting vi-mode )

source $ZSH/oh-my-zsh.sh

alias ra="ranger"
alias vi="nvim"

export PATH=/root/Program/shells/:$PATH

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

server() {
	ssh root@39.101.204.135
}

export PROXY=0
proxy () {
	if [ $PROXY -eq 0 ];
	then
		export hostip=$(cat /etc/resolv.conf |grep -oP '(?<=nameserver\ ).*')
		export http_proxy="http://${hostip}:1080"
		export https_proxy="http://${hostip}:1080"
		export PROXY=1
		echo "HTTP Proxy on"
	else
		unset http_proxy
		unset https_proxy
		export PROXY=0
		echo "HTTP Proxy off"
	fi
}
